import type { Metadata } from "next";
// import { Sarabun } from "next/font/google"
import "./globals.css";

// const sarabun = Sarabun({
//   weight:'400',
//   subsets:['thai']
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`bg-[#0039a6] text-white m-3 space-y-2`}
        // ${sarabun.className}
      >
      
      {children}
      </body>
    </html>
  );
}